brunch010/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'', include('brunch010_app.urls', namespace='brunch010')),
    url(r'^markdownx/', include('markdownx.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

brunch010_app/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views


urlpatterns = [
	# Post
	url(r'^$', views.post_home, name='post_home'),								
	url(r'^create/$', views.post_create, name='post_create'),					
	url(r'^posts/(?P<id>\d+)$', views.post_detail, name='post_detail'),			
	url(r'^posts/(?P<id>\d+)/edit/$', views.post_update, name='post_update'),	
	url(r'^delete/$', views.post_delete, name='post_delete'),					
	# Login
	url(r'^login/$', auth_views.login, {'template_name': 'login.html'}, name='user_login'),
	url(r'^logout/$', views.logout_view, name='user_logout'),

]

brunch010_app/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from markdownx.models import MarkdownxField
from markdownx.utils import markdownify
from django.utils import timezone


class PostManager(models.Manager):
	def active(self, *args, **kwargs):
		return super(PostManager, self).filter(draft=False).filter(publish__lte=timezone.now())

def upload_location(instance, filename):
	return "%s/%s" % (instance.id, filename)


class Post(models.Model):
	user = models.ForeignKey(User, on_delete=models.CASCADE)
	categories = models.CharField(max_length=25)
	title = models.CharField(max_length=180)
	email = models.EmailField()
	content = MarkdownxField()
	draft = models.BooleanField(default=True)
	publish = models.DateField(auto_now=True, auto_now_add=False)
	date_added = models.DateTimeField(auto_now_add=True)
	date_updated = models.DateTimeField(auto_now=True)
	timestamp = models.DateTimeField(auto_now=False, auto_now_add=True)
	height_field = models.IntegerField(default=0)
	width_field = models.IntegerField(default=0)
	image = models.ImageField(upload_to=upload_location, null=True, blank=True, height_field="height_field", width_field="width_field")
	objects = PostManager()


	def __str__(self):
		return self.title
	

	def get_absolute_url(self):
		return reverse("brunch010:post_detail", kwargs={"id": self.id})


	def get_html(self):
		return markdownify(self.content)


	def get_next(self):
		next_id = Post.objects.filter(id__gt=self.id)
		if next_id:
			return next_id.first()
		return False

	
	def get_next_draft(self):
		next_id = Post.objects.filter(id__gt=self.id).exclude(draft=True)
		if next_id:
			return next_id.first()
		return False


	def get_prev(self):
		prev_id = Post.objects.filter(id__lt=self.id).order_by('-id')			
		if prev_id:
			return prev_id.first()
		return False


	def get_prev_draft(self):
		prev_id = Post.objects.filter(id__lt=self.id).order_by('-id').exclude(draft=True)
		if prev_id:
			return prev_id.first()
		return False			

brunch010_app/forms.py
from django import forms
from .models import Post
from markdownx.fields import MarkdownxFormField

class PostForm(forms.ModelForm):
	content = MarkdownxFormField()
	
	class Meta:
		model = Post
		fields = [
			"user",
			"title",
			"categories",
			"draft",
			"image",
			"content",	

		]

brunch010_app/views.py
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from .forms import PostForm
from .models import Post


'''Main Home Page'''
def post_home(request):
	queryset_list = Post.objects.active().order_by('-id')
	if request.user.is_superuser:
		queryset_list = Post.objects.all().order_by('-id')

	paginator = Paginator(queryset_list, 6)
	page = request.GET.get('page')
	try:
		queryset = paginator.page(page)
	except PageNotAnInteger:
		queryset = paginator.page(1)
	except EmptyPage:
		queryset = paginator.page(paginator.num_pages)

	context = {
		"queryset": queryset,
	}

	return render(request, 'index.html', context)


'''Create Post Page'''
@login_required
def post_create(request):
	if not request.user.is_superuser:
		raise Http404

	if request.method != 'POST':
		form = PostForm()
	else:
		form = PostForm(request.POST, request.FILES)
		if form.is_valid():
			form.save()
			return HttpResponseRedirect(reverse('brunch010:post_home'))

	context = {
		"form": form
	}

	return render(request, 'forms.html', context)


'''Detailed Post Page'''
def post_detail(request, id):
	instance = get_object_or_404(Post, id=id)
	if instance.draft:	
		if not request.user.is_superuser:
			raise Http404
	context = {
		"instance": instance,
	}

	return render(request, 'detail.html', context)


'''Update Post Page'''
@login_required
def post_update(request, id=None):
	instance = get_object_or_404(Post, id=id)
	if request.method != 'POST':
		form = PostForm(instance=instance)
	else:	
		form = PostForm(request.POST, request.FILES, instance=instance)
		if form.is_valid():
			instance = form.save(commit=False)
			instance.save()
			return HttpResponseRedirect(instance.get_absolute_url())

	context = {
		"form": form,
	}

	return render(request, 'forms.html', context)


'''Delete Post Page'''
@login_required
def post_delete(request):
	context = {}

	return render(request, 'delete.html', context)


'''Logout the user'''
def logout_view(request):
	logout(request)
	return HttpResponseRedirect(reverse('brunch010:post_home'))

brunch010_app/templates/about.html
<p>/About Page</p>

brunch010_app/templates/base.html
{% load staticfiles %}
<!--DOCTYPE html -->
<html lang="en">
<head>
  <meta charset="utf-8">
   <meta http-equiv="X-UA-Compatible" content="IE=edge">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <title>Brunch</title>
   <link href="https://fonts.googleapis.com/css?family=Ubuntu" rel="stylesheet">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css">
	<link rel="stylesheet" href="{% static 'css/base.css' %}">
</head>

<body>

	<nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <!-- <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
          </button> -->
          <a class="navbar-brand" href="{% url 'brunch010:post_home' %}">Brunch</a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li><a href="{% url 'brunch010:post_home' %}">Home</a></li>
            <li><a href="#">About</a></li>
            <li><a href="#">Projects</a></li>
            <li><a href="#">Contacts</a></li>
          </ul>          
          <ul class="nav navbar-right">
          {% if user.is_authenticated %}
            <li><a href="{% url 'brunch010:user_logout' %}">Logout</a></li>
          {% endif %}
          </ul>
          
        </div><!--/.nav-collapse -->        
      </div>
    </nav>

<div class="container">
{% block content %}
{% endblock content %}  
</div>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>

</html>

brunch010_app/templates/delete.html
<p>Delete Page</p>

brunch010_app/templates/detail.html
{% extends "base.html" %}

{% block content %}

<div class="col-md-8 col-md-offset-2">
<div class="row">
<div class="col-md-4 col-custom-text">
	{% if instance.get_prev %}
	{% if user.is_authenticated %}
	  <a href="{{ instance.get_prev.id }}">Previous Topic</a></p>
	{% else %}
	  <a href="{{ instance.get_prev_draft.id }}">Previous Topic</a></p>
	{% endif %}  
	{% endif %}
</div>
<div class="col-md-4 col-md-offset-4 col-custom-text col-custom-next">
	{% if instance.get_next %}
	{% if user.is_authenticated %}
	  <a href="{{ instance.get_next.id }}">Next Topic</a></p>
	 {% else %}
	  <a href="{{ instance.get_next_draft.id }}">Next Topic</a></p>
	{% endif %}
	{% endif %}
</div>
</div>
	<div class="detail-title">{{ instance.title }} 
	  <small>{% if instance.draft %}<span class="custom-draft"> Draft</span>{% endif %}</small>
	</div><hr/>
	{% if instance.image %}
      <img src="{{ instance.image.url }}" class="img-responsive" alt="image" />
	{% endif %}

	<p>{{ instance.get_html|safe }}</p><br/><hr/>
<div class="col-custom-text">
	<a href="{% url 'brunch010:post_home' %}">Back to Main Page</a></p>
</div>	
</div>
{% endblock content %}

brunch010_app/templates/forms.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% block content %}
{{ form.media }}

<div class="row">
  <h1>Form</h1><hr>
  <form method="POST" action="" enctype="multipart/form-data">
    {% csrf_token%}
    {{ form|crispy }}
    <hr>
    <input type="submit" class="btn btn-default" value="Submit" />
  </form>

</div>
{% endblock content %}

brunch010_app/templates/index.html
{% extends "base.html" %}

{% block content %}

{% for query in queryset %}
<div class="row">
<div class="col-md-8">
	<div class="title">
	  <a href="{{ query.get_absolute_url }}"><strong>{{ query.title }}</strong></a>
	  <small>{% if query.draft %}<span class="custom-draft"> Draft</span>{% endif %}</small>
	</div>
	  </br><p>{{ query.get_html|striptags|truncatechars_html:185 }}</p>
	<div class="label-text-color">	  
	  <span class="label-text-color">Post by </span>
      <span class="label label-primary">{{ query.user.get_full_name }}</span>
      <!-- <span class="label label-default">{{ query.date_added|date:'M d, Y' }}</span> -->
      <span class="label label-success">{{ query.publish|date:'M d, Y' }}</span>
      <span class="label label-danger">{{ query.categories }}</span>
	</div>	
</div> <!-- col-md-9 -->

<div class="col-md-2 col-custom">
  {% if query.image %}
    <img src="{{ query.image.url }}" class="img-responsive" alt="image" />
  {% endif %}
</div>
</div> <!-- row -->
<hr class="hr-custom">
{% endfor %}

	<div class="pagination">
	    <span class="step-links">
	        {% if queryset.has_previous %}
	          <a href="?page={{ queryset.previous_page_number }}"><span class="label-page label-danger">Prev</span></a>	       
	        {% endif %}	        
	        {% if queryset.has_next %}
	          <a href="?page={{ queryset.next_page_number }}"><span class="label-page label-info">Next</span></a>
	        {% endif %}	     
	    </span>
	</div>

{% endblock content %}

brunch010_app/templates/login.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
<div class="col-md-4 col-md-offset-2">

	<form method="POST" action="{% url 'brunch010:user_login' %}">
	{% csrf_token %}
	{{ form|crispy }}
	<button class="btn btn-default btn-lg" type="submit" name="login">Log In</button>
	<input type="hidden" name="next" value="{% url 'brunch010:post_home' %}" />
	</form>
	
</div>
{% endblock content %}

brunch010_app/templates/markdownx/widget2.html
{% load staticfiles %}

<div class="markdownx row">
  <div class="col-md-6">
    {% include 'django/forms/widgets/textarea.html' %}
  </div>
  <div class="col-md-6">
    <div class="markdownx-preview"></div>
  </div>
</div>